# Generated by Django 5.1.7 on 2025-03-25 10:57

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (JPG, JPEG, or PNG). Maximum size: 5MB, dimensions: 800x800 or smaller.', null=True, upload_to='profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), users.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('analyst', 'Analyst'), ('marketer', 'Marketer'), ('researcher', 'Researcher')], default='researcher', max_length=20),
        ),
    ]
