# Generated by Django 5.1.7 on 2025-03-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_role_alter_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('analyst', 'Data Analyst'), ('researcher', 'Researcher'), ('general', 'General User')], default='general', max_length=20),
        ),
    ]
