# Generated by Django 5.1.7 on 2025-03-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('analyst', 'Analyst'), ('researcher', 'Researcher'), ('marketer', 'Marketer')], default='researcher', max_length=20),
        ),
    ]
