import csv
import os

def restore_training_data():
    """Restore the original training data in the correct format."""
    models_dir = os.path.join(os.getcwd(), 'models', 'sentiment_analysis')
    training_file = os.path.join(models_dir, 'training_data.csv')
    
    # Original data from the file we saw earlier
    original_data = [
        ["Job creation in Binga is  priority.", "positive"],
        ["Corruption in Chitungwiza needs to be addressed.", "negative"],
        ["Healthcare services in Kwekwe are lacking.", "neutral"],
        ["We need more investment in technology in Zimbabwe.", "positive"],
        ["Business opportunities in Bulawayo are growing.", "positive"],
        ["Tourism in Masvingo is on the rise!", "positive"],
        ["Corruption in councils needs to be addressed.", "negative"],
        ["Inflation in Gweru is a major issue.", "negative"],
        ["Healthcare services in  are lacking.", "negative"],
        ["Great leadership in Mutare!", "positive"],
        ["Youth unemployment in Marondera is a crisis.", "positive"],
        ["Tourism in Kariba is on the rise!", "positive"],
        ["Youth unemployment in Mberengwa is a crisis.", "negative"],
        ["Education in Bindura is key for our future.", "positive"],
        ["Inflation in Kariba is a major issue.", "negative"],
        ["Education is driving Binga development.", "positive"],
        ["Tourism in Kariba is on the rise", "neutral"],
        ["Political unrest in Bulawayo is concerning.", "negative"],
        ["Great leadership in Binga", "positive"],
        ["Political unrest and violence is concerning.", "negative"],
        ["The economy in Harare is improving!", "positive"],
        ["Community engagement in Negande Kriba rural rural is essential.", "neutral"],
        ["The economy in Chivhu is improving ", "positive"],
        ["Inflation in Zvipani is a major issue.", "negative"],
        ["Business opportunities in Bulawayo are growing.", "positive"],
        ["The economy in karoi is improving especially during tobacco season", "neutral"],
        ["Animals are putting Binga people life in danger", "neutral"],
        ["Healthcare services in Binga are lacking.", "negative"],
        ["The infrastructure in Harare is in bad state", "negative"],
        ["Education in Zvimba west district is being taken serious", "positive"],
        ["Investment in tourism in Masvingo is crucial.", "neutral"],
        ["Corruption in Chitungwiza needs to be addressed.", "neutral"],
        ["Youth unemployment in Marondera is a crisis.", "neutral"],
        ["Political unrest in Bulawayo is concerning.", "negative"],
        ["Great leadership in Mutare!", "positive"],
        ["Corruption in Chitungwiza needs to be addressed.", "neutral"],
        ["Great leadership are cooking something big in Gokwe Chitekete", "positive"],
        ["Political unrest in Bulawayo is concerning.", "neutral"],
        ["Inflation in Kariba Mola area is a major issue.", "positive"],
        ["Education in Bindura is key for our future.", "neutral"],
        ["Great leadership in Mutare is moving to another level", "positive"],
        ["Corruption in land distribution needs to be addressed.", "negative"],
        ["The Displaced local people in Zambezi valley are languishing in poverty", "negative"],
        ["Youth unemployment in Marondera is a crisis.", "negative"],
        ["Tourism in Victoria Falls is on the rise!", "positive"],
        ["Corruption needs to be addressed.", "neutral"],
        ["Business opportunities in Bulawayo are growing.", "positive"],
        ["The economy in Harare is improving!", "positive"],
        ["The infrastructure in Harare is improving.", "positive"],
        ["Inflation hit Simuchembu area is a major issue.", "negative"],
        ["Business opportunities in Siakobvu are growing.", "positive"],
        ["Tourism in Marongora safara is on the rise!", "positive"],
        ["Healthcare services in Jongola area are lacking.", "negative"],
        ["Inflation in Gweru is a major issue.", "negative"],
        ["Corruption in Chitungwiza needs to be addressed.", "negative"],
        ["Business opportunities in Chegutu are growing.", "positive"],
        ["Healthcare services in Kwekwe are lacking.", "neutral"],
        ["Tourism in Masvingo is on the rise!", "positive"],
        ["Political unrest in Bulawayo is concerning.", "negative"],
        ["Investment in tourism in Masvingo is crucial.", "neutral"],
        ["Education in Mutoko  is key for our future.", "positive"],
        ["Education in Gokwe is key for our future.", "positive"],
        ["Youth unemployment in Marondera is a crisis.", "negative"],
        ["Job creation in Gweru is a priority.", "neutral"],
        ["The food price is too high local remote area", "negative"],
        ["The life of people in fishing industry is on risk during rain and windy condtions", "positive"],
        ["We need more investment in technology in Zimbabwe.", "neutral"],
        ["Tourism in Matopo hills is on the rise!", "neutral"],
        ["Business opportunities in Bulawayo are growing.", "positive"],
        ["Job creation in Gweru is a priority.", "positive"],
        ["Business opportunities in Bulawayo are growing.", "positive"],
        ["Job creation in Gweru is a priority.", "positive"],
        ["Education in Bubi District is key for our future.", "positive"],
        ["Education  is key for our future.", "neutral"],
        ["Investment in tourism in Binga is crucial.", "positive"],
        ["The infrastructure in Harare is improving.", "positive"],
        ["Community engagement in Mutare is essential.", "positive"],
        ["Great leadership in Karoi council", "positive"],
        ["Business opportunities in Bulawayo are growing.", "positive"],
        ["Corruption in Chitungwiza needs to be addressed.", "negative"],
        ["Inflation in Gweru is a major issue.", "negative"],
        ["Political unrest in makuti is concerning.", "negative"],
        ["The economy in Kariba is improving through fishing industry", "positive"],
        ["The infrastructure in Zvimba is improving.", "positive"],
        ["Job creation in Manjolo area in Binga is a priority.", "positive"],
        ["Community engagement in Mutare is essential.", "positive"],
        ["Business opportunities in Bulawayo are growing.", "positive"],
        ["Education in Chitekete is key for our future.", "positive"],
        ["Business opportunities in Magunje are growing.", "neutral"],
        ["The infrastructure in Goromonzi is improving.", "neutral"],
        ["Great leadership in Chirundu", "positive"],
        ["Job creation in Kasimhure is a priority.", "positive"],
        ["Tourism in Masvingo is being affected by economic conditions", "negative"],
        ["Great leadership in Chivhu", "positive"],
        ["We need more investment in technology in Zimbabwe.", "positive"],
        ["The economy in Chinhoyi is improving!", "positive"],
        ["Inflation in tengwe is a major issue.", "negative"],
        ["Community engagement in Nyamapanda", "positive"],
        ["Great leadership in Mvurwi", "positive"],
        ["Poor resources monitoring hit some local councils", "negative"],
        ["Democraric leadership style is being taking place Nyami nyami rural district Council", "positive"],
        ["Some police officers in Zimbabwe they are nolonger pracitising honest as per the job core values ", "negative"],
        ["Poor governance is destroying us", "negative"],
        ["inflation is under control in zimbabwe", "positive"],
        ["Inflation in Gweru is a major issue.", "negative"],
        ["Community engagement in Jongola is essential.", "neutral"],
        ["Corruption in Chitungwiza needs to be addressed.", "negative"],
        ["Business opportunities in Bulawayo are growing.", "neutral"],
        ["Inflation in Gweru is a major issue.", "negative"],
        ["Education in Bindura is key for our future.", "positive"],
        ["Inflation in Gweru is a major issue.", "negative"],
        ["Corruption in Chitungwiza needs to be addressed.", "negative"],
        ["The infrastructure in Harare is improving.", "positive"],
        ["The infrastructure in Harare is improving.", "positive"],
        ["The economy in Harare is improving!", "positive"],
        ["Job creation in Gweru is a priority.", "positive"],
        ["Inflation in Gweru is a major issue.", "negative"],
        ["Political unrest in Bulawayo is concerning.", "negative"],
        ["Youth unemployment in Marondera is a crisis.", "negative"],
        ["Education in Bindura is key for our future.", "positive"],
        ["Healthcare services in Kwekwe are lacking.", "negative"],
        ["Great leadership in Mutare!", "positive"],
        ["Business opportunities in Bulawayo are growing.", "positive"],
        ["The infrastructure in Harare is improving.", "positive"],
        ["Healthcare services in Kwekwe are lacking.", "negative"],
        ["Youth unemployment in Marondera is a crisis.", "negative"],
        ["Youth unemployment in Marondera is a crisis.", "negative"],
        ["Business opportunities in Bulawayo are growing.", "positive"],
        ["We need more investment in technology in Zimbabwe.", "positive"],
        ["We need more investment in technology and science  in Zimbabwe.", "positive"],
        ["Great leadership in Mutare!", "positive"],
        ["Political unrest in Bulawayo is concerning.", "negative"],
        ["Business opportunities in Bulawayo are growing.", "positive"],
        ["Political unrest in Bulawayo is concerning.", "negative"],
        ["The infrastructure in Harare is improving.", "positive"],
        ["Youth unemployment in Marondera is a crisis.", "negative"],
        ["Inflation in Gweru is a major issue.", "negative"],
        ["The economy in Harare is improving!", "positive"],
        ["The economy in Harare is improving!", "positive"],
        ["Corruption in Chitungwiza needs to be addressed.", "negative"],
        ["Business opportunities in Bulawayo are growing.", "positive"],
        ["Education in Bindura is key for our future.", "positive"],
        ["Education in Bindura is key for our future.", "positive"],
        ["The economy in Harare is improving!", "positive"],
        ["Political unrest in Bulawayo is concerning.", "negative"],
        ["Healthcare services in Kwekwe are lacking.", "negative"],
        ["We need more investment in agriculturein Zimbabwe.", "positive"],
        ["Political unrest in Bulawayo is concerning.", "negative"],
        ["Investment in tourism in Masvingo is crucial.", "positive"],
        ["Healthcare services in Kwekwe are lacking.", "negative"],
        ["The economy in Harare is improving!", "positive"],
        ["Political unrest in Bulawayo is concerning.", "negative"],
        ["Tourism in Masvingo is on the rise!", "positive"],
        ["We need more investment in technology in Zimbabwe.", "positive"],
        ["Investment in tourism in Masvingo is crucial.", "positive"],
        ["Youth unemployment in Marondera is a crisis.", "negative"],
        ["Business opportunities in Bulawayo are growing.", "positive"],
        ["Political unrest in Bulawayo is concerning.", "negative"],
        ["We need more investment in technology in Zimbabwe.", "positive"],
        ["corruption is killing our economy", "negative"],
        ["Youth unemployment in Marondera is a crisis.", "negative"],
        ["Great leadership in Mutare!", "positive"],
        ["The infrastructure in Siabbuwa is improving.", "positive"],
        ["We need more investment in transport  sector", "positive"],
        ["Education in Bindura is key for our future.", "positive"],
        ["Job creation in Gweru is a priority.", "positive"],
        ["Education in Bindura is key for our future.", "positive"],
        ["Job creation in Gweru is a priority.", "positive"],
        ["Tourism in Binga hotspring is on the rise!", "positive"],
        ["Corruption in Chitungwiza needs to be addressed.", "negative"],
        ["We need more investment in technology in Zimbabwe.", "positive"],
        ["Inflation in Gweru is a major issue.", "negative"],
        ["Youth unemployment in Marondera is a crisis.", "negative"],
        ["Political unrest in Bulawayo is concerning.", "negative"],
        ["Great leadership in Musambakaruma and Makande", "positive"],
        ["Investment in tourism in Masvingo is crucial.", "positive"],
        ["Investment in tourism in Masvingo is crucial.", "positive"],
        ["Investment in tourism in Centenary is crucial.", "positive"],
        ["Political unrest in Bulawayo is concerning.", "negative"],
        ["Tourism in Masvingo is on the rise!", "positive"],
        ["Education in Bindura is key for our future.", "positive"],
        ["Inflation in Negande is a major issue.", "negative"],
        ["Healthcare services in siakobvu are lacking.", "negative"],
        ["Job creation in Mola is a priority.", "positive"],
        ["Job creation in Negande is a priority.", "positive"],
        ["Job creation in Nebiri area is a priority.", "positive"],
        ["Business opportunities in Bulawayo are growing.", "positive"],
        ["Political unrest in Bulawayo is concerning.", "negative"],
        ["Corruption in Chinhoyi council needs to be addressed.", "negative"],
        ["Education in Bindura is key for our future.", "positive"],
        ["Youth unemployment in Marondera is a crisis.", "negative"],
        ["Political unrest in Bulawayo is concerning.", "negative"],
        ["Political unrest in Bulawayo is concerning.", "negative"],
        ["Youth unemployment in Marondera is a crisis.", "negative"],
        ["Great leadership in Mutare are turing the city into world class city", "positive"],
        ["Political unrest in Hwange is concerning.", "negative"],
        ["Investment in tourism in Masvingo is crucial.", "positive"],
        ["Great leadership in African parks safari in kariba", "positive"],
        ["Customers happily received our products in the market", "neutral"]
    ]
    
    print(f"Restoring {len(original_data)} records to: {training_file}")
    
    # Write the data in the correct format
    with open(training_file, 'w', newline='', encoding='utf-8') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(['text', 'sentiment'])
        writer.writerows(original_data)
    
    print(f"Successfully restored {len(original_data)} records")
    print("File format: text,sentiment")

if __name__ == "__main__":
    restore_training_data() 