# Generated by Django 5.1.7 on 2025-03-25 06:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('query_type', models.CharField(choices=[('sentiment', 'Sentiment Analysis'), ('trend', 'Trend Analysis'), ('comparison', 'Comparison Analysis'), ('demographic', 'Demographic Analysis')], max_length=20)),
                ('parameters', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_interval', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Analytics Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analytics.analyticsquery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('excel', 'Excel')], max_length=10)),
                ('file', models.FileField(upload_to='exports/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('download_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='analytics.analyticsquery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
